#!/usr/bin/env sh
# Wrappers
alias lf="lfrun"
alias cat="bat"

alias editbashrc="vi ~/.bashrc; source ~/.bashrc"

alias sudo="sudo "
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first --hide="__pycache__/"" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"\
	ll="ls -lash"\
    pm="python -m"\
    pi="pip install --user"\
    chwp="bash ~/.config/wallpaper/set_feh_bg.sh"\
    rmwp="python ~/.config/wallpaper/forget_wp.py"\
    python="ipython"\
    goodsteam="LD_PRELOAD=/usr/lib/libfreetype.so steam"\
    python="ipython"\
    routine="python /home/eyal/documents/programmation/training_programs/routine/myroutine.py"\
    teaching="bash /home/eyal/documents/programmation/scripts/teacher_screen.sh"\
    chrome="google-chrome-stable"\

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" vi="nvim" # Use neovim for vim if present.
alias mutt="neomutt"

vf() { fzf | xargs -r -I % $EDITOR % ;}

# Commands
alias cp='cp -iv'
alias rcp='rsync -v --progress'
alias rmv='rsync -v --progress --remove-source-files'
alias mv='mv -iv'
alias rm='rm -iv'
alias rmdir='rmdir -v'
alias ln='ln -v'
alias chmod="chmod -c"
alias chown="chown -c"
alias mkdir="mkdir -v"

if command -v colordiff > /dev/null 2>&1; then
    alias diff="colordiff -Nuar"
else
    alias diff="diff -Nuar"
fi

alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias ls='ls --color=auto --human-readable --group-directories-first --classify'
alias ll='ls --color=auto --human-readable --group-directories-first --classify -l'
alias lla='ls --color=auto --human-readable --group-directories-first --classify -la'


# Scripts
alias gpush="bash ~/.config/scripts/git_add_commit_push.sh"
alias grpush="bash ~/.config/scripts/git_add_commit_push.sh routine"
alias wacomconfig="bash ~/.config/scripts/configure_xsetwacom_tablet.sh"


# DONT USE RM ANYMORE
alias cfi="vi ~/.config/i3/config"
alias t="rmtrash"
alias td="rmtrash -r"
alias rm="echo Use 'tr', or the full path i.e. /bin/rm"

# Navigation
alias ,cnf="cd ~/.config"
alias ,work="cd ~/documents/work/"
alias ,doc="cd ~/documents/"
alias ,army="cd ~/documents/army/"
alias ,di="cd ~/documents/work/dev-institute"
alias ,maayan="cd ~/documents/work/private_classes/maayan"
alias ,2py="cd ~/documents/work/dev-institute/classes/python2"
alias ,3py="cd ~/documents/work/dev-institute/classes/python3"
alias ,el="cd ~/documents/work/dev-institute/classes/elijah"
alias ,prog="cd ~/documents/programmation"
alias ,unif="cd ~/documents/university"
alias ,ulin="cd ~/documents/university/courses_notes/linear_algebra_1"
alias ,udisc="cd ~/documents/university/courses_notes/discrete_maths_1"
alias ,ujav="cd ~/documents/university/courses_notes/java_1"
alias ,u="cd ~/documents/university"
# TEMPORARY Navigation
alias ,raph="cd ~/documents/work/freelance/raph_zeitoun/leslibraires"

alias dwm-config="/home/eyal/dwm-install/dwm-6.2/current-dwm-luke/"
alias xcopy="xclip -selection clipboard"

# Files opener
alias zrc="vi ~/.config/zsh/.zshrc"
alias vrc="vi ~/.config/nvim/init.vim.d/init.vim"
alias vinit="vi ~/.config/nvim/init.vim.d/"
alias vplg="vi ~/.config/nvim/init.vim.d/plugins.vim"
alias vsht="vi ~/.config/nvim/init.vim.d/shortcuts.vim"
alias vfnc="vi ~/.config/nvim/init.vim.d/functions.vim"
alias vrtp="vi ~/.config/nvim/init.vim.d/runtime/"
alias vtex="vi ~/.config/nvim/init.vim.d/runtime/UltiSnips/tex.snippets"
alias vsnips="vi ~/.config/nvim/init.vim.d/runtime/UltiSnips/"
alias lfrc="vi ~/.config/lf/lfrc"
alias lfdoc="lf -doc | less"
alias alrc="vi ~/.aliasrc; source ~/.aliasrc"

# Files manipulation
alias cleantex="bash ~/.config/scripts/clean_latex_compilation_files.sh"

# Tmux
alias xn="tmux new-session"
alias xnv="tmux new-session \; split-window -v"
alias xnh="tmux new-session \; split-window -h"
alias xls="tmux ls"
alias xat="tmux attach-session -t "
