#!/usr/bin/env sh

userresources=$HOME/.config/Xorg/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f "$HOME/.config/Xorg/xprofile" ] && . $HOME/.config/Xorg/xprofile


# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#bash $HOME/.config/.screenlayout/auto_layout.sh
#bash $HOME/.config/wallpaper/set_feh_bg.sh

#################################################################################
# Window manager:
# DWM:
#[ -f "$HOME/.config/dwm/statusbar.sh" ] && . ~/.config/dwm/statusbar.sh &
#exec dwm

# i3:
#exec i3 

# xfce:
#exec startxfce4

# qtile:
exec qtile start
##################################################################################
