export CONFIG_DIR="/.autodirect/mtrsysgwork/eshukrun/.config"

if [[ -f "$CONFIG_DIR/commonprofile" ]]; then
    source $CONFIG_DIR/commonprofile
else
    echo "CONFIG_DIR is not found !! This is very important, please set the CONFIG_DIR var in every profile/rc file"
fi

# Mount NVIDIA remote directory
# Should be added as a launch agent
# https://apple.stackexchange.com/questions/192600/how-to-run-custom-applescript-in-the-background-at-all-times
#if [[ -z "$(mount | grep mtrsysgwork)" ]]; then
#    osascript -e 'mount volume "smb://eshukrun@mtrlabfs02/mtrsysgwork"'
#fi


if [ -x /usr/libexec/path_helper ]; then
   eval `/usr/libexec/path_helper -s`
fi
