export LAST_DIR_FILE="$HOME/.caching_files/.last_dir"
export LAST_LAST_DIR_FILE="$HOME/.caching_files/.last_last_dir"
export EDITOR="/opt/homebrew/bin/nvim"
export TMP="$HOME/tmp"
export TEMP="$TMP"
export TMPDIR="$TMP"


